version: '3.8'
services:
  node:
    restart: always
    build: .
    ports:
      - 5000:5000
    volumes:
      - ./:/app
    env_file: .env
  mongo:
    image: mongo
    ports:
      - 27018:27017
    volumes:
      - mongodb:/data/db
volumes:
  mongodb: